name: nexus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - typer
  - pyyaml
  - openbabel
  - vina
  - meeko
  - rdkit
  - pydantic
  - pytest
  - pip
  - pip:
    - rcsb-api
