name: nexus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - typer
  - pyyaml
  - pydantic
  - openbabel
  - vina
  - meeko
  - rdkit
  - openmm
  - cuda=12.0
  - scipy
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - rcsb-api
