name: nexus_test
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Language & Runtimes
  - python=3.11
  
  # Data Science & Math Core
  - numpy<2.0
  - scipy
  - pandas
  - matplotlib
  
  # Cheminformatics & Simulation
  - openbabel
  - rdkit=2025.03.6
  - meeko=0.7.1
  - vina
  - openmm
  
  # Utilities & Config
  - pydantic>=2.0
  - typer
  - pyyaml
  
  # Pip setup and packages
  - pip
  - pip:
    - rcsb-api
    