libs:
  chimerax: "/usr/local/chimerax/bin/ChimeraX"
  chimera: "/usr/local/chimera/chimera-1.8/bin/chimera"

  mgltools: "/localscratch/kbui/Apps/mgltools_1.5.7/mgltools_x86_64Linux2_1.5.7/"
  dock_home: "/localscratch/kbui/Apps/dock6/"

  obabel: "obabel"
  parallel: "parallel"
  vina: "vina"

common:
  project_name: vina_mpro_catalytic
  working_dir: "/localscratch/kbui/Comp_DD/artifacts"
  results_dir: "/localscratch/kbui/Comp_DD/results/"

  receptor: "/localscratch/kbui/Comp_DD/data/6W63.pdb"
  ligands_csv: "/localscratch/kbui/Comp_DD/data/ligands_list.csv"
  
  pocket_selection: "chain A and resi 41+145+140+143+144+145+163+166"
  padding: 5.0
  n_jobs: 16
  max_poses: 8

vina:
  exhaustiveness: 32
  num_modes: 8
  reference: "data/ref_ligand.pdb" # Set to None if use pocket_selection
  cpu: 1
  write_box: True

dock6:
  max_orientations: 5000
  radius: 10.0
