libs:
  chimerax: "/usr/local/chimerax/bin/ChimeraX"
  chimera: "/usr/local/chimera/chimera-1.8/bin/chimera"

common:
  project_name: vina_mpro
  working_dir: "/localscratch/kbui/NexusMol/examples/_artifacts"
  results_dir: "/localscratch/kbui/NexusMol/examples/_results"

  padding: 4.0 # Extra buffer distance for the search grid
  n_jobs: 16 # Total number of concurrent jobs, adjust to your machine
  max_poses: 8 # Total number of pose scores to be displayed in summary csv

receptors:
  source: "/localscratch/kbui/NexusMol/examples/receptors/final"
  suffix: ".pdb" # used when `source` is a directory, ignored if `source` is a file

  pocket_option: "selection"
  selection: "/A:41,145,163,164,172" # Residues at the catalytic site for Mpro
  reference: null
  reference_suffix: null

ligands:
  source: "/localscratch/kbui/NexusMol/examples/ligands/vina"
  suffix: "_prepared.pdbqt" # used when `source` is a directory, ignored if `source` is a file

vina:
  exhaustiveness: 32 # Higher for more accuracy at more cost
  num_modes: 8 # Total number of poses to be generated by vina

# You can write anything here, and they will be wrote to a JSON file in results directory
# CSV summary file paths will also be included here for easy parsing
metadata:
  tool: vina
  grid: catalytic_site
  settings: default
