common:
  # You can also use output files from `md build` in results/6W63_mol4_solvated
  # The input here is dialanine, which is a much smaller system for illustration purposes
  # Dialnine is "ACE-ALA-NME", which has 3 residues, so :1-3
  # If you decide to use 6W63_mol4_solvated, the mask is ":1-611" 
  # (2 chains with 305 residues each, and 1 ligand as an additional residue)
  prmtop: inputs/ALA.prmtop
  inpcrd: inputs/ALA.inpcrd
  mask: ":1-3"
  temp: 300.0
  dt: 0.002
  cut: 10.0
  job_name: AMBER_DiAla
  output_dir: results

### All time units are in picoseconds (ps)
### All restraints units are in kcal/(mol * A^2)

min:
  n_min_runs: 7 # consecutive
  ncyc: 1000 # Initial cycles using Steepest Descent, then switch to Conjugate Gradient for the rest
  maxcyc: 5000 # ncyc and maxcyc is for each 
  restraints: [10.0, 5.0, 2.0, 1.0, 0.5, 0.1, 0.0] # the list length must match n_min_runs

heat:
  mid_temp: 100.0 # used for flexible heating strategy
  time_mid_temp: 100.0 # time mark until system reaches mid_temp
  time_temp: 500.0 # time mark until system reaches temp, time2 > time1
  total_time: 1000.0 # total_time > time2 > time1 
  restraint: 10.0 # One value for the whole heating phase

eq:
  n_eq_runs: 7 # consecutive
  eq_time: 100.0 # time for each eq runs
  restraints: [10.0, 5.0, 2.0, 1.0, 0.5, 0.1, 0.0] # the list length must match n_eq_runs

prod:
  num_seeds: 1 # Independent seeds
  rand_time: 200.0 # Additional equilibration time for each seed randomization
  prod_time: 1000.0 # Total production time, adjust according to goal
  prod_freq: 10.0 # Frequency to report mdout, write trajectory, and save trajectory. Too frequent can hurt performance.

engine:
  program: amber
  